---
- name: restart supervisor
  shell: service supervisor restart
  become: yes
  become_method: sudo

- name: start supervisor
  service: name=supervisor state=started
  become: yes
  become_method: sudo

- name: enable supervisor
  service: name=supervisor enabled=yes
  become: yes
  become_method: sudo
