---
- hosts: vagrant
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes
  become_method: sudo

  roles:
    - common
    - nginx
    - redis
    - supervisor
    - postgresql
    - project_data
    - gunicorn


- hosts: production
  vars_files:
    - vars.yml
  gather_facts: true
  become: yes
  become_method: sudo

  roles:
    - common
    - nginx
    - redis
    - newrelic
    - supervisor
    - project_data
    - gunicorn
